name: hakyll CI

on:
  push:
    branches: 
      - master
      - test

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Hakyll build workflow
      uses: zfhrp6/hakyll-build-action@v0.1.1
